### PR TITLE
Add Permissions Policy directive browsing-topics

### LINKED ISSUE #22: Consider adding `browser-topics` restriction by default
As discussed in #20 `browser-topics` is the new replacement for `interest-cohort`.

This will be able to be disabled by setting ` permission policy of `browser-topics=()` (in similar way that `interest-cohort` was disabled). At present this is not available in any browser and so may still change but, once it becomes available, we should consider setting this default to disable this for privacy reasons.

### PR DESCRIPTION
**Pull request by bershanskiy**
This PR adds Permissions Policy directive `browsing-topics` which controls access to [The Topics API](https://developer.chrome.com/docs/privacy-sandbox/topics/). This API is Chromium-only and is still in Origin Trial (in Chrome 101 to 104 until [August 29](https://developer.chrome.com/origintrials/#/view_trial/771241436187197441)) and it might land in Chrome 105 which is scheduled to be released on August 30.

Fixes #22.
Related to #20 and #21.

### CODE REVIEW

**Comment by tunetheweb** [comment]
> it might land in Chrome 105 which is scheduled to be released on August 30.

There's nothing on the [Chrome Roadmap](https://chromestatus.com/roadmap) for this for 105 and typically there's a release or two (often more) while the results of the origin trail are analysed.

So I'm still a -1 on this change for now while it is still experimental.

But, full disclosure, I've joined the Chrome team since we last discussed this so will leave the decision to someone else. Though I'm working on web performance not privacy so know no more than you on this particular feature 😁

**Comment by bershanskiy** [comment]
This PR just got less relevant, might become relevant by year 2023.

Based on [this Chromium blog post](https://developer.chrome.com/blog/expanding-privacy-sandbox-testing/), looks like launch of Privacy Sandbox (including Topics API) is postponed a bit further. Starting with Chrome 104, OT will include stable users, but most likely sites will still need to explicitly opt in to be included in Topics calculation.

**Comment by dmarti** [comment]
They're planning to push "Topics API" out to "all Chrome users" in the 2nd half of 2023: https://developer.chrome.com/en/blog/expanding-privacy-sandbox-testing-2023/

**Comment by Jonakemon** [comment]
In Chrome 115 this became a thing again: https://developer.chrome.com/blog/privacy-sandbox-launch/. I'm keen on disabling browsing-topics by default to enhance privacy. @tunetheweb, what do you think?

**Comment by tunetheweb** [comment]
As I work on the Chrome team now I'll bow out of commenting whether this is a good change or not, but no objections from me as it's no longer behind a flag.

**Comment by Jonakemon** [comment]
@bershanskiy, what do you think? Would you be willing to rebase your PR? If not, I'll create a new one this weekend to merge your change.

**Comment by bershanskiy** [comment]
@Jonakemon Yes, sure I'll rebase and test it (within the next day).

**Comment by bershanskiy** [comment]
@Jonakemon I rebased the PR, and just to make sure everything is OK ran unit tests on CI (ran manually in my repo and then they were automatically here), and tested manually locally and am happy with the way this works now. Please merge whenever it is convenient.

Also, is there a plan to make a release any time soon? Thanks!

**Comment by Jonakemon** [comment]
@bershanskiy I really appreciate the rebase, thanks! After the other PR is merged, I'll propose a deploy.

**Comment by Jonakemon** [comment]
@bershanskiy a new release was just published on Pypi https://pypi.org/project/flask-talisman/1.1.0/. Thanks for all the help :)

**Pull request merged**
